"""Let's Encrypt / certbot orchestration.

Vreckan serves its web UI over TLS. By default it uses a self-signed
certificate (generated by ``run_https.py``). When Let's Encrypt is enabled
(via ``VRECKAN_LE_*`` env vars or the admin Certificates page), this module
issues and renews real certificates by running the official
``certbot/dns-cloudflare`` image as a *transient* container: it is started,
waits for it to exit, streams its logs on failure, and removes it.

The certbot container mounts the app's ``/data/le`` storage directly (the
same bind mount or named volume the app uses for that path, auto-detected at
runtime). Certificates therefore persist across container re-creations and
are readable by the app without a separate host bind mount.

Two auth methods are supported:

* ``dns-cloudflare`` (default) — Cloudflare DNS-01. A ``cloudflare.ini``
  credentials file (email + API token) is written into the shared volume and
  passed to certbot. No inbound HTTP is required, so it works behind a
  reverse proxy or on a non-public host.
* ``http-01`` — ACME HTTP-01. The ACME server fetches
  ``/.well-known/acme-challenge/...`` from the domain; the webroot is the
  shared volume.

All functions are async and use ``asyncio.to_thread`` for the blocking
Docker SDK calls, matching the rest of the codebase.
"""

import asyncio
import logging
import os
import socket
from datetime import datetime, timezone
from typing import Dict, List, Optional

logger = logging.getLogger(__name__)

# The official certbot image with the Cloudflare DNS plugin bundled.
CERTBOT_IMAGE = os.environ.get("VRECKAN_LE_CERTBOT_IMAGE", "certbot/dns-cloudflare:latest")

# Named volume shared between the certbot container (/etc/letsencrypt) and the
# app container (/data/le). Overridable for tests / custom layouts.
LE_VOLUME = os.environ.get("VRECKAN_LE_VOLUME", "vreckan-le")

# Where the app reads certbot-issued certificates from (the shared volume).
LE_APP_CERT_DIR = os.environ.get("VRECKAN_LE_APP_CERT_DIR", "/data/le")

# Where the app looks for a host-provided /etc/letsencrypt (checked first).
LE_HOST_CERT_DIR = os.environ.get("VRECKAN_LE_HOST_CERT_DIR", "/etc/letsencrypt")

# certbot's default paths *inside* the certbot container.
CERTBOT_CERT_DIR = "/etc/letsencrypt"
CERTBOT_CREDENTIALS = "/etc/letsencrypt/cloudflare.ini"


def _primary_domain(domains: List[str]) -> str:
    """The primary domain (first in the list) — certbot names the live
    directory after it."""
    return domains[0] if domains else ""


def cert_paths(domains: List[str]) -> Optional[Dict[str, str]]:
    """Return the cert/key paths for the given domains, or ``None`` if no
    certificate is present.

    The host ``/etc/letsencrypt`` is checked first (an operator may mount a
    pre-existing cert there); the shared-volume path (``/data/le``) is the
    fallback for certbot-issued certs.
    """
    primary = _primary_domain(domains)
    if not primary:
        return None
    for base in (LE_HOST_CERT_DIR, LE_APP_CERT_DIR):
        cert = os.path.join(base, "live", primary, "cert.pem")
        key = os.path.join(base, "live", primary, "privkey.pem")
        if os.path.isfile(cert) and os.path.isfile(key):
            return {"cert": cert, "key": key, "base": base}
    return None


def cert_expiry(cert_path: str) -> Optional[datetime]:
    """Parse a PEM certificate and return its notAfter as an aware UTC
    ``datetime``, or ``None`` if it cannot be read/parsed."""
    try:
        from cryptography import x509

        with open(cert_path, "rb") as f:
            cert = x509.load_pem_x509_certificate(f.read())
        # cryptography >= 42 exposes an aware ``not_valid_after_utc``; older
        # versions only have the (naive) ``not_valid_after``.
        exp = getattr(cert, "not_valid_after_utc", None)
        if exp is None:
            exp = cert.not_valid_after
            if exp.tzinfo is None:
                exp = exp.replace(tzinfo=timezone.utc)
        return exp.astimezone(timezone.utc)
    except Exception as e:  # noqa: BLE001 - any parse/read failure -> None
        logger.warning(f"Could not parse certificate expiry for {cert_path}: {e}")
        return None


def cert_status(domains: List[str]) -> Dict:
    """Describe the current certificate for the given domains.

    Returns a dict with:
      * ``present`` — a cert+key were found (host or shared-volume path).
      * ``source`` — ``"host"`` or ``"volume"`` (where it was found).
      * ``cert`` / ``key`` — the paths (or ``None``).
      * ``expiry`` — ISO-8601 expiry string (or ``None``).
      * ``days_remaining`` — whole days until expiry (negative if expired).
      * ``valid`` — present and not yet expired.
    """
    paths = cert_paths(domains)
    if not paths:
        return {
            "present": False,
            "source": None,
            "cert": None,
            "key": None,
            "expiry": None,
            "days_remaining": None,
            "valid": False,
        }
    exp = cert_expiry(paths["cert"])
    now = datetime.now(timezone.utc)
    days_remaining = None
    valid = False
    if exp is not None:
        days_remaining = (exp - now).days
        valid = exp > now
    source = "host" if paths["base"] == LE_HOST_CERT_DIR else "volume"
    return {
        "present": True,
        "source": source,
        "cert": paths["cert"],
        "key": paths["key"],
        "expiry": exp.isoformat() if exp else None,
        "days_remaining": days_remaining,
        "valid": valid,
    }


def needs_renewal(days_remaining: Optional[int], renew_before_days: int) -> bool:
    """True when the cert should be renewed: it is present and expires within
    ``renew_before_days`` days (or is already expired)."""
    if days_remaining is None:
        return False
    return days_remaining <= renew_before_days


def write_cloudflare_credentials(email: str, token: str) -> str:
    """Write the Cloudflare credentials file into the shared volume (at the
    app-side path) and return its path. certbot reads it from the container
    path via the volume mount.

    The keys use the ``dns_cloudflare_`` prefix the plugin expects (it looks
    up ``dns_cloudflare_api_token`` / ``dns_cloudflare_email``). A token alone
    is sufficient for DNS-01; the email line is only written when no token is
    set, because the plugin rejects a file that contains both.

    No ``[dns_cloudflare]`` section header is written: the plugin reads the
    file with configobj and looks the keys up at the *top level*, so a
    section header would nest them and the lookup would miss them."""
    path = os.path.join(LE_APP_CERT_DIR, "cloudflare.ini")
    os.makedirs(os.path.dirname(path), exist_ok=True)
    with open(path, "w") as f:
        if token:
            f.write(f"dns_cloudflare_api_token = {token}\n")
        if email and not token:
            f.write(f"dns_cloudflare_email = {email}\n")
    # Restrict permissions: the file holds an API token.
    try:
        os.chmod(path, 0o600)
    except OSError:
        pass
    return path


def certbot_args(auth: str, domains: List[str], staging: bool, renew: bool = False) -> List[str]:
    """Build the certbot command-line arguments.

    * ``renew=False`` → ``certonly`` (issue a fresh cert).
    * ``renew=True``  → ``renew`` (renew any cert that is due).
    * ``auth="dns-cloudflare"`` → DNS-01 with the credentials file.
    * ``auth="http-01"`` → HTTP-01 with the shared volume as webroot.
    """
    args: List[str] = []
    if renew:
        args.append("renew")
    else:
        args.append("certonly")
    args += ["--non-interactive", "--agree-tos", "--register-unsafely-without-email"]
    if staging:
        args.append("--staging")
    if auth == "http-01":
        args += ["--http-01", f"--webroot-root={CERTBOT_CERT_DIR}"]
    else:  # dns-cloudflare (default)
        args += ["--dns-cloudflare", f"--dns-cloudflare-credentials={CERTBOT_CREDENTIALS}"]
    for d in domains:
        args += ["-d", d]
    return args


def _app_le_mount(client) -> str:
    """Detect how the app container's ``/data/le`` is backed and return the
    mount spec (a host path or a named-volume name) that a transient certbot
    container should bind at ``/etc/letsencrypt`` so both see the same
    storage.

    The app's ``/data/le`` is a sub-path of its ``/data`` mount, so the
    backing source is read from the app container's own mount list (located
    by its hostname). This handles both the dev layout (``/data`` is a host
    bind mount, so ``/data/le`` is a host sub-path) and the production
    layout (``/data`` is a named volume). Falls back to the ``LE_VOLUME``
    named volume when the app container cannot be resolved.
    """
    try:
        cont = client.containers.get(socket.gethostname())
        for m in cont.attrs.get("Mounts") or []:
            if m.get("Destination") == "/data":
                if m.get("Type") == "volume":
                    return m.get("Name") or LE_VOLUME
                src = m.get("Source") or ""
                if src:
                    return src.rstrip("/") + "/le"
    except Exception as e:  # noqa: BLE001 - fall back to the named volume
        logger.warning(f"Could not detect the app's /data/le mount ({e}); "
                       f"falling back to the '{LE_VOLUME}' volume.")
    return LE_VOLUME


async def run_certbot(
    args: List[str],
    *,
    client=None,
    image: str = CERTBOT_IMAGE,
    volume: str = LE_VOLUME,
    timeout: int = 300,
) -> Dict:
    """Run a transient certbot container with the given arguments.

    Returns ``{"ok": bool, "exit_code": int|None, "logs": str}``. The
    container is always removed afterwards (even on failure). ``client`` may
    be injected for tests; otherwise ``docker.from_env()`` is used.

    ``volume`` is the storage mounted at certbot's ``/etc/letsencrypt``: by
    default the app's own ``/data/le`` storage (auto-detected, see
    :func:`_app_le_mount`) so the Cloudflare credentials file and the issued
    certificates are shared with the app; pass an explicit host path or
    volume name to override.
    """
    import docker
    from docker.errors import DockerException

    if client is None:
        client = await asyncio.to_thread(docker.from_env)

    if volume is LE_VOLUME:
        volume = await asyncio.to_thread(_app_le_mount, client)

    container = None
    try:
        container = await asyncio.to_thread(
            client.containers.run,
            image,
            args,
            detach=True,
            volumes={volume: {"bind": CERTBOT_CERT_DIR, "mode": "rw"}},
            remove=False,
        )
        res = await asyncio.to_thread(container.wait, timeout=timeout)
        exit_code = res.get("StatusCode")
        logs_b = await asyncio.to_thread(container.logs)
        logs = logs_b.decode("utf-8", "replace") if isinstance(logs_b, bytes) else str(logs_b)
        ok = exit_code == 0
        if not ok:
            logger.error(f"certbot exited {exit_code}:\n{logs}")
        return {"ok": ok, "exit_code": exit_code, "logs": logs}
    except DockerException as e:
        logger.error(f"certbot container error: {e}")
        return {"ok": False, "exit_code": None, "logs": str(e)}
    finally:
        if container is not None:
            try:
                await asyncio.to_thread(container.remove, force=True)
            except Exception as e:  # noqa: BLE001
                logger.warning(f"Could not remove certbot container: {e}")

async def effective_le_config():
    """Build a settings-like object holding the *effective* LE settings
    (``app_settings`` DB override → env → default). Both the startup path
    (``run_https.py``) and the background renewal loop (``api.py``) use this
    so a value edited on the admin Certificates page takes effect without a
    container restart."""
    from server.settings import settings

    class _Cfg:
        pass

    cfg = _Cfg()
    cfg.le_enabled = bool(await settings.get_setting("le_enabled"))
    cfg.le_domains = await settings.get_setting("le_domains") or ""
    cfg.le_auth = await settings.get_setting("le_auth") or "dns-cloudflare"
    cfg.le_staging = bool(await settings.get_setting("le_staging"))
    cfg.le_cloudflare_email = await settings.get_setting("le_cloudflare_email") or ""
    cfg.le_cloudflare_token = await settings.get_setting("le_cloudflare_token") or ""
    cfg.le_auto_renew = bool(await settings.get_setting("le_auto_renew"))
    cfg.le_renew_check_hours = int(await settings.get_setting("le_renew_check_hours") or 6)
    cfg.le_renew_before_days = int(await settings.get_setting("le_renew_before_days") or 30)
    return cfg

async def ensure_le_cert(settings, *, client=None) -> Dict:
    """Startup: make sure a valid Let's Encrypt certificate exists.

    No-op when LE is disabled or no domains are configured. If the current
    cert is missing or expired, issue a fresh one. Returns a status dict
    (see :func:`cert_status`) plus an ``issued`` flag.
    """
    domains = [d.strip() for d in str(settings.le_domains).split(",") if d.strip()]
    if not settings.le_enabled:
        return {**cert_status(domains), "issued": False, "enabled": False}
    if not domains:
        logger.warning("LE enabled but no domains configured (le_domains).")
        return {**cert_status(domains), "issued": False, "enabled": True}

    status = cert_status(domains)
    if status["valid"]:
        logger.info(f"LE certificate valid until {status['expiry']} ({status['days_remaining']}d).")
        return {**status, "issued": False, "enabled": True}

    # (Re)issue.
    if settings.le_auth == "http-01":
        pass  # webroot is the shared volume; nothing to pre-write.
    else:
        # A Cloudflare API token is sufficient for DNS-01; the account email
        # is only needed for the legacy email + API-key method.
        if not settings.le_cloudflare_token:
            logger.warning("LE DNS-01 enabled but Cloudflare API token not set.")
            return {**status, "issued": False, "enabled": True}
        write_cloudflare_credentials(settings.le_cloudflare_email, settings.le_cloudflare_token)

    args = certbot_args(settings.le_auth, domains, settings.le_staging, renew=False)
    result = await run_certbot(args, client=client)
    status = cert_status(domains)
    return {**status, "issued": result["ok"], "enabled": True}


async def renew_le_cert(settings, *, client=None) -> Dict:
    """Background renewal: renew the cert if it is within the renewal window.

    Returns a status dict plus ``renewed`` (True when a renew was attempted
    and succeeded) and ``due`` (True when the cert was within the window).
    """
    domains = [d.strip() for d in str(settings.le_domains).split(",") if d.strip()]
    if not settings.le_enabled or not domains:
        return {**cert_status(domains), "renewed": False, "due": False, "enabled": bool(settings.le_enabled)}

    status = cert_status(domains)
    due = needs_renewal(status["days_remaining"], settings.le_renew_before_days)
    if not due:
        return {**status, "renewed": False, "due": False, "enabled": True}

    if settings.le_auth != "http-01":
        # A Cloudflare API token is sufficient for DNS-01; the account email
        # is only needed for the legacy email + API-key method.
        if not settings.le_cloudflare_token:
            logger.warning("LE DNS-01 enabled but Cloudflare API token not set.")
            return {**status, "renewed": False, "due": True, "enabled": True}
        write_cloudflare_credentials(settings.le_cloudflare_email, settings.le_cloudflare_token)
    args = certbot_args(settings.le_auth, domains, settings.le_staging, renew=True)
    result = await run_certbot(args, client=client)
    status = cert_status(domains)
    return {**status, "renewed": result["ok"], "due": True, "enabled": True}
